name: 'olist_analysis' # 1. 改名，反映你的业务目标
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# 核心配置区域
models:
  olist_analysis: # 2. 这里必须和顶部的 name 保持完全一致
    # 定义 Staging 层：存放最基础的清洗代码
    staging:
      +materialized: view      # 意义：保持数据实时性，不额外占用 BQ 存储空间
    
    # 定义 Marts 层：存放最终给 BI 报表用的数据
    marts:
      +materialized: table     # 意义：存为实体表，极大提升下游 BI 工具的查询速度