sources:
  - name: olist_raw
    database: project-2c55b1ac-af96-4683-a80
    schema: olist_raw
    tables:
      - name: olist_orders_dataset               # 原始表名 1
      - name: olist_order_items_dataset          # 原始表名 2
      - name: olist_customers_dataset            # 原始表名 3
      - name: olist_products_dataset             # 原始表名 4
      - name: olist_order_payments_dataset       # 原始表名 5
      - name: olist_geolocation_dataset        # 原始表名 6
      - name: olist_sellers_dataset              # 原始表名 7
      - name: product_category_name_translation # 原始表名 8

# test
models:
  # orders 表
  - name: stg_orders
    description: "Testing orders table"
    columns:
      - name: order_id
        description: "the primary key of this orders table"
        tests:
          - unique
          - not_null

  # customers 表
  - name: stg_customers
    description: "巴西电商客户基础信息表"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "客户唯一标识(一个 unique_id 可能对应多个 customer_id)"
        tests:
          - not_null

  # geolocation 表     
  - name: stg_geolocation
    description: "地理位置采样数据，包含重复的邮编前缀，建议下游进行聚合处理。"
    columns:
      - name: geolocation_zip_code_prefix
        tests:
          - not_null  -- 只要保证有邮编就行，不要求唯一
  
  # items 表     
  - name: stg_order_items
    description: "该表格详细记录了客户订单中的各项单品信息"
    columns:
      - name: order_id
        tests:
          - not_null 
      - name: order_item_id
        tests:
          - not_null 
